version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Zona horaria (ajusta según tu ubicación)
      - GENERIC_TIMEZONE=America/Bogota
      - TZ=America/Bogota
    volumes:
      # Volumen para persistir datos de n8n (credenciales, workflows, etc.)
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biblioteca-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - n8n-network
 
volumes:
  n8n_data:
    name: n8n_data

networks:
  n8n-network:
    name: n8n-network

